In [16]:
import numpy as np

In [17]:
## Ques -01 Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr = np.array([1,2,3,6,4,5])
reversed_arr = arr[::-1]
reversed_arr

array([5, 4, 6, 3, 2, 1])

In [18]:
# Ques -01(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
            #NumPy in-built methods

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flatten1 = array1.flatten()
flatten1

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [19]:
flatten2 = array1.ravel()
flatten2

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

In [20]:
## Ques-01 (c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

result = np.array_equal(arr1, arr2)
print(result)

True


In [21]:
## Ques-01 (d)
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_freq_val_x = values[np.argmax(counts)]

indices_x = np.where(x == most_freq_val_x)[0]

print("Most frequent value in x:", most_freq_val_x)
print("Indices:", indices_x)

Most frequent value in x: 1
Indices: [0 5 7 8 9]


In [22]:
## Ques-01 (e)

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

total_sum = gfg.sum()
print("Sum of all elements:", total_sum)

row_sum = gfg.sum(axis=1)
print("Sum of all elements row-wise:\n", row_sum)

col_sum = gfg.sum(axis=0)
print("Sum of all elements column-wise:\n", col_sum)


Sum of all elements: 45
Sum of all elements row-wise:
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:
 [[20  9 16]]


In [23]:
## Ques-01 (f)
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])

# i. Sum of diagonal elements
diagonal_sum = np.trace(n_array)
print("i. Sum of diagonal elements:", diagonal_sum)

# ii. Eigenvalues of the matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("ii. Eigenvalues of matrix:", eigenvalues)

# iii. Eigenvectors of the matrix
print("iii. Eigenvectors of matrix:\n", eigenvectors)

# iv. Inverse of matrix
inverse_matrix = np.linalg.inv(n_array)
print("iv. Inverse of matrix:\n", inverse_matrix)

# v. Determinant of matrix
determinant = np.linalg.det(n_array)
print("v. Determinant of matrix:", determinant)


i. Sum of diagonal elements: 176
ii. Eigenvalues of matrix: [98.16835147 28.097044   49.73460452]
iii. Eigenvectors of matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
iv. Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
v. Determinant of matrix: 137180.0000000001


In [24]:
## Ques-01 (g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

product1 = np.dot(p1, q1)
print("i. Product of p1 and q1:\n", product1)

covariance1 = np.cov(p1.flatten(), q1.flatten())
print("i. Covariance matrix:\n", covariance1)


i. Product of p1 and q1:
 [[16 19]
 [26 31]]
i. Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [25]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])  # Shape: (3x2)
q2 = np.array([[4, 5, 1], [6, 7, 2]])    # Shape: (2x3)

product2 = np.dot(p2, q2)
print("ii. Product of p2 and q2:\n", product2)

covariance2 = np.cov(p2.flatten(), q2.flatten())
print("ii. Covariance matrix:\n", covariance2)


ii. Product of p2 and q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
ii. Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [26]:
## Ques-01 (h)

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x, y)
print("Inner Product:\n", inner_product)

outer_product = np.outer(x.flatten(), y.flatten())
print("Outer Product:\n", outer_product)

from itertools import product

# Cartesian product of rows from x and y
cartesian_product = np.array([np.concatenate([a, b]) for a, b in product(x, y)])
print("Cartesian Product:\n", cartesian_product)

Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


In [27]:
## Ques-02
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)
print("Absolute:\n", abs_array)

# ii. Percentiles (25th, 50th, 75th)
flattened = array.flatten()
p25 = np.percentile(flattened, 25)
p50 = np.percentile(flattened, 50)
p75 = np.percentile(flattened, 75)
print(f"25th percentile: {p25}, 50th: {p50}, 75th: {p75}")

# Percentile for each column
print("25th Percentile (columns):", np.percentile(array, 25, axis=0))
print("50th Percentile (columns):", np.percentile(array, 50, axis=0))
print("75th Percentile (columns):", np.percentile(array, 75, axis=0))

# Percentile for each row
print("25th Percentile (rows):", np.percentile(array, 25, axis=1))
print("50th Percentile (rows):", np.percentile(array, 50, axis=1))
print("75th Percentile (rows):", np.percentile(array, 75, axis=1))

# iii. Mean, Median, Std Dev
print("Mean (flat):", np.mean(flattened))
print("Median (flat):", np.median(flattened))
print("Std Dev (flat):", np.std(flattened))

print("Mean (columns):", np.mean(array, axis=0))
print("Median (columns):", np.median(array, axis=0))
print("Std Dev (columns):", np.std(array, axis=0))

print("Mean (rows):", np.mean(array, axis=1))
print("Median (rows):", np.median(array, axis=1))
print("Std Dev (rows):", np.std(array, axis=1))



Absolute:
 [[1 2 3]
 [4 5 6]]
25th percentile: -3.5, 50th: -0.5, 75th: 2.5
25th Percentile (columns): [-2.75 -0.25 -3.75]
50th Percentile (columns): [-1.5  1.5 -1.5]
75th Percentile (columns): [-0.25  3.25  0.75]
25th Percentile (rows): [-0.5 -5. ]
50th Percentile (rows): [ 1. -4.]
75th Percentile (rows): [2.  0.5]
Mean (flat): -0.5
Median (flat): -0.5
Std Dev (flat): 3.8622100754188224
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std Dev (columns): [2.5 3.5 4.5]
Mean (rows): [ 0.66666667 -1.66666667]
Median (rows): [ 1. -4.]
Std Dev (rows): [2.05480467 4.78423336]


In [28]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Floor, Ceiling, Truncated, Rounded
print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [29]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_4 = np.sort(array)[:4]

# iv. 5 largest elements
largest_5 = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_4)
print("5 largest elements:", largest_5)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [30]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integers_only = array[array == array.astype(int)]

# ii. Float elements only (not whole numbers)
floats_only = array[array != array.astype(int)]

print("Integer elements only:", integers_only)
print("Float elements only:", floats_only)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [32]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:
        np.savetxt("grayscale_image.txt", arr, fmt='%d')
        print(f"{path} is a Grayscale image. Saved as 'grayscale_image.txt'")
    else:
        reshaped = arr.reshape(-1, arr.shape[-1])
        np.savetxt("rgb_image.txt", reshaped, fmt='%d')
        print(f"{path} is an RGB image. Saved as 'rgb_image.txt'")

img_to_array("gray_image.jpg")
img_to_array("color_image.jpg")

print("\n--- Loaded from grayscale_image.txt ---")
gray = np.loadtxt("grayscale_image.txt", dtype=int)
print(gray)

print("\n--- Loaded from rgb_image.txt ---")
rgb = np.loadtxt("rgb_image.txt", dtype=int).reshape(-1, 3)
print(rgb)

gray_image.jpg is a Grayscale image. Saved as 'grayscale_image.txt'
color_image.jpg is an RGB image. Saved as 'rgb_image.txt'

--- Loaded from grayscale_image.txt ---
[[ 0  0  0 ... 48 48 49]
 [ 0  0  0 ... 48 49 49]
 [ 0  0  1 ... 49 49 50]
 ...
 [48 48 49 ... 96 97 97]
 [48 49 49 ... 97 97 97]
 [49 49 50 ... 97 97 98]]

--- Loaded from rgb_image.txt ---
[[  1   1   1]
 [  1   1   1]
 [  3   1   2]
 ...
 [193 197 196]
 [196 198 197]
 [197 199 198]]
